### ISSUE TITLE
Compatibility with latest Intellij EAP (181.*) builds

### ISSUE THREAD

**Issue by nsiniakevich** [OpherV/gitflow4idea#184]
I can't install this plugin on latest intellij EAP 2018.1 since it's limited to 2017.3 version in [plugin.xml](https://github.com/OpherV/gitflow4idea/blob/develop/META-INF/plugin.xml#L13)

<img width="239" alt="screen shot 2018-02-13 at 2 46 52 pm" src="https://user-images.githubusercontent.com/8200716/36148376-dc97cbb2-10cc-11e8-9d2e-ec5f17dea7c7.png">

https://www.jetbrains.com/idea/nextversion/

**Comment by tiagoncardoso** [comment]
Hi nsiniakevich! I had the same error when I tried to install the git_flow integration from disk (I don't even found it in the repository). But I did found a solution:

1. Download the latest version of plugin on https://plugins.jetbrains.com/plugin/7315-git-flow-integration (a .jar file);
2. Open the .jar file with some file compression manager (like winrar or something like that);
3. In compression manager, you'll see 3 folders (com, gitflow and META-INF). Open the file META-INF/plugin.xml (do it with some simple text editor).
4. In the line 13, change:
`<idea-version since-build="162.0" until-build="173.*"/>`
to
`<idea-version since-build="162.0" until-build="181.*"/>`
and save the file (update that in the .jar file);
5. Open your IDE and go to de plugins instalation (settings);
6. Choose the option "Install plugin from the disk" and select the updated file .jar;
7. Restart your IDE.

That was what I did here, and works fine. Hope this helps.

**Comment by nsiniakevich** [comment]
@tiagoncardoso thanks for sharing this.

@OpherV I can make a pull request, but I don't understand how to make jar file from sources to verify that everything is working as it should work. Could you explain to make a jar file?

**Comment by OpherV** [comment]
@nsiniakevich 
A getting started guide to the project can be found here: https://github.com/OpherV/gitflow4idea/blob/develop/docs/project_setup.md

It's easy to just change the string so that the plugin runs on a new EAP - the real time consuming part is testing that each feature works on the new version, on all platforms, then fixing any bugs that may arise...

**Comment by jaxn** [comment]
I'm happy to provide testing help.  It doesn't look like there is a pull request yet, is anyone working on a branch?

**Comment by nsiniakevich** [comment]
No pull request because it should be tested before PR 🙂

I just realized that @tiagoncardoso already test this, so we can make and merge PR.

**Comment by hosswald** [comment]
The plugin works for me in 181.4203.6 after I changed `idea-version` in plugin.xml to `<idea-version since-build="162.0" until-build="189.*"/>`

**Comment by tibuurcio** [comment]
Hi guys, I've done the above to try and use the plugin on 181.* and got a NullPointerException while trying to create a new feature branch. I've tried to re-init git flow with `git flow init -f` but got the same thing. Please tell me if the error stack would be useful somehow and other tests I could do to help :)

**Comment by moaavesh** [comment]
tried update to <idea-version since-build="162.0" until-build="181.*"/> but did not work for me.

**Comment by OpherV** [comment]
Version 0.6.4

**Comment by Zorvalt** [comment]
Hello, I think something went wrong when updating the plugin in the jetbrains repository :
https://plugins.jetbrains.com/plugin/7315-git-flow-integration

![image](https://user-images.githubusercontent.com/1624057/38200230-d0d83a90-3693-11e8-937b-b666367fcc51.png)

Therefore, it is still not possible to update the plugin in 181.*

**Comment by OpherV** [comment]
@Zorvalt There was an issue with 0.6.4 and 181 builds, so I changed the compatibility definition. A new version will be out soon which fixes this.
