### ISSUE TITLE
UI Freeze

### ISSUE THREAD

**Issue by CrazyCoder** [OpherV/gitflow4idea#198]
Plug-in seems to hang IntelliJ IDEA.

> Git Flow Integration (0.6.5.1)

```
"AWT-EventQueue-0 2018.1.2#IU-181.4668.68 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b29" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.util.concurrency.Semaphore$Sync@31aa0841
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:109)
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:99)
	at com.intellij.execution.process.ProcessHandler.waitFor(ProcessHandler.java:87)
	at com.intellij.execution.process.BaseOSProcessHandler.waitFor(BaseOSProcessHandler.java:236)
	at git4idea.commands.GitTextHandler.waitForProcess(GitTextHandler.java:144)
	at git4idea.commands.GitHandler.runInCurrentThread(GitHandler.java:440)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:145)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:119)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:43)
	at git4idea.commands.GitImpl.runCommand(GitImpl.java:56)
	at git4idea.config.GitConfigUtil.getValue(GitConfigUtil.java:96)
	at gitflow.GitflowConfigUtil.getFeaturePrefix(GitflowConfigUtil.java:63)
	at gitflow.GitflowBranchUtil.hasGitflow(GitflowBranchUtil.java:53)
	at gitflow.ui.GitflowWidget.update(GitflowWidget.java:168)
	at gitflow.ui.GitflowWidget.access$100(GitflowWidget.java:54)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:143)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
```

https://youtrack.jetbrains.com/issue/IDEA-190524

**Comment by OpherV** [comment]
Can you please provide the output of the git console when this happens? (version control tab -> console tab)

**Comment by roland-d** [comment]
@OpherV I can't check anymore since I updated to:
PhpStorm 2018.2 EAP
Build #PS-182.2371.32, built on May 17, 2018
PhpStorm EAP User
Expiration date: June 16, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

Here the Gitflow plugin is no longer visible in the statusbar but what I saw in the console log was that it was asking for `Which branch should be used for bringing forth production releases?` and then I had two options develop or master as these were my only branches.

**Comment by roland-d** [comment]
@OpherV I was able to find some time to reproduce this issue, here is the output of my Console:
```
13:16:28.513: [pwt-image] git -c core.quotepath=false -c log.showSignature=false flow init
Which branch should be used for bringing forth production releases?
   - develop
   - feature/zoom-tools
   - hotfix/select-folder-links
   - master
   - refactor-javascript
   - refactor-perfectimage
```

**Comment by bbakermmc** [comment]
Same Issue on 18.1.3.  You basically have to run it in terminal first

10:57:15.804: [PROJECT] git -c core.quotepath=false -c log.showSignature=false flow init
Which branch should be used for bringing forth production releases?
   - develop
   - master

**Comment by OpherV** [comment]
@bbakermmc what do you mean by  " You basically have to run it in terminal first"?
Can you please give me steps on how to reproduce?

**Comment by GreenImp** [comment]
I'm also able to reproduce this issue. Clicking "Init Repo" seems to hang. Checking the Version Control Console shows the following:

```
10:45:49.759: [PROJECT] git -c core.quotepath=false -c log.showSignature=false flow init
Which branch should be used for bringing forth production releases?
   - develop
```

However, I then quite PHPStorm and re-opened, pulled down the `master` branch (I previously only had the `develop` branch), and re-tried.
This time, it worked fine and didn't hang.

When it worked, I saw this output in the console:

```
11:02:43.562: [gradpad-2017] git -c core.quotepath=false -c log.showSignature=false flow init -d
Using default branch names.
Which branch should be used for bringing forth production releases?
   - develop
   - master
Branch name for production releases: [master] 
Which branch should be used for integration of the "next release"?
   - develop
Branch name for "next release" development: [develop] 
How to name your supporting branch prefixes?
Feature branches? [feature/] 
Release branches? [release/] 
Hotfix branches? [hotfix/] 
Support branches? [support/] 
Version tag prefix? [] 
```

**Comment by OpherV** [comment]
Can anyone provide a public repo of a project that reproduces this? I can't fix the bug if I'm unable to reproduce

**Comment by roland-d** [comment]
@OpherV The public repo you can use is https://github.com/joomla/joomla-cms I get the same issue with that repo.

**Comment by OpherV** [comment]
@roland-d 
I just tested with a fresh clone of the repo- it has no 'master' branch, rather the default is 'staging':
![image](https://user-images.githubusercontent.com/3951311/48311018-5eeebe00-e5a1-11e8-8062-1493ce558e8c.png)

Which leads to gitflow throwing an error (not gitflow4idea):
![image](https://user-images.githubusercontent.com/3951311/48311030-8cd40280-e5a1-11e8-9844-7a9684751654.png)


But I don't get any freeze. Is your experience different?

**Comment by roland-d** [comment]
@OpherV You are correct, Joomla does not have the master branch. However regardless of this the issue can be seen. Just for testing you can also take this `https://github.com/nette/tracy` repo. There the same happens.

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/359377/48317675-d1898900-e5f5-11e8-9cb4-04f61f5e5b35.png">

Here is what I did on the Tracy repo to get this.
1. I clicked Init repo
2. Set these settings:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/359377/48317681-f41ba200-e5f5-11e8-8124-dcfa3e54327e.png">
3. Click OK
4. Then you see the first screenshot in the Log tab. Where git is asking which branch to use for production releases.

So when I execute this command `git -c core.quotepath=false -c log.showSignature=false flow init` on the command line I can enter the branch name, now this is not possible. I figured this is what I already set in step 2.

Rather than a freeze it is rather the task `Initializing repo` that runs until the project is closed.

**Comment by OpherV** [comment]
@iasemenov I think you might be able to help - I've looked into this and it seems like an issue with IntellIJ's `GitLineHandler` if I'm not mistaken (or maybe I'm misusing it)

When you run this command:
```
/usr/bin/git -c core.quotepath=false -c log.showSignature=false flow init
```

The output is:
![image](https://user-images.githubusercontent.com/3951311/48336929-3252a900-e66a-11e8-8a59-12a30769ca7c.png)

With the last line "Branch name for production releases" waiting for input. This output isn't being caught by the GitLineHandlers's `onTextAvailableMethod``, which leads to my plugin getting stuck.
I assume it's because that's some sort of blocking input?

(Last line received by the method is this:)
![image](https://user-images.githubusercontent.com/3951311/48336572-4c3fbc00-e669-11e8-88b6-fb2972ed3005.png)

How can I catch this line to provide output? Is there some other method for blocking text other than `onTextAvailableMethod`?

**Comment by iasemenov** [comment]
@OpherV 
You are misusing the handler a bit (this if fine, since the proper way is only available since 18.2), but this is not the issue here. It looks like `Branch name for production releases` and all other "response awaiting" lines are not terminated by line separators and `GitLineHandler` relies on separators to collect the input (text is sent to listeners only when line has ended).

In your case you should extend `GitTextHandler` to be able to read incomplete lines and use `GitHandler.setInputProcessor` method to provide input. Keep in mind that `onTextAvailable` and input processor are called in separate threads, so you should use smth like `SynchronousQueue` to pass messages between listener and processor.

**Comment by OpherV** [comment]
@iasemenov Thanks so much!  I started working in that direction but ran into a few walls:

1. `GitImpl`, which my `GitFlowImpl` extends from has `runCommand` which only accepts `GitLineHandler`. So even if I implement my own handling with extensions of`GitTextHandler`, I won't be able to use `runCommand`. I'd really like to avoid rewriting `GitImpl` in my plugin as I feel that's going to be another rabbit hole. 

2. Seems like even `GitTextHandler` doesn't accept non-terminated lines on `onTextAvailable`, so the line handling logic is done within the `ProcessListener` which I don't have access to?

I'm a little confused at all this architecture - and wish to solve my users' bug as quickly as possible so any suggestion would be welcome

**Comment by iasemenov** [comment]
@OpherV 
1. Yes, `GitImpl` works only with `GitLineHandler` and there's not much point to allow for more at the moment. I meant that you can use it as reference for writing something similar, but much more simple (I assume you generally don't need remote auth, locking and elaborate output collection).
2. Hmmm, that's strange. Output processing is done around `com.intellij.execution.process.BaseOSProcessHandler#createOutputDataReader()`. Default behavior (which is used in `GitTextHandler`) is to send even non-terminated lines.
I'd suggest to try and set a bunch of breakpoints in `com.intellij.util.io.BaseOutputReader`. Also check if these lines and sent to STDOUT or somewhere else.

**Comment by OpherV** [comment]
Closed thank to @bmwsedee's contribution!

**Comment by mf-social** [comment]
This is still not working correctly and can be reproduced easily.

1 - Start a new project in android studio.

2 - Select VCS > Create git repository

3 - Commit whatever files you want

4 - Create develop branch (and commit some changes if you want, makes no difference)

5 - click Init Repo on the plugin

6 - Select 'master' for production branch and 'develop' for next branch

7 - click OK

Hangs forever on 'Initializing repo' 😢 

Manually initialising the repo with `git -c core.quotepath=false -c log.showSignature=false flow init` and restarting Android Studio works fine, and after this the plugin works as expected.  Just Init Repo button is not having it for some reason.

**Comment by bmwsedee** [comment]
With these steps I wasn't able to reproduce, unfortunately. Can you tell what versions of Android Studio and the plugin you are using? And are you on a Windows-machine?

**Comment by mf-social** [comment]
Sure,

Studio...

```
    Android Studio 3.3
    Build #AI-182.5107.16.33.5199772, built on December 25, 2018
    JRE: 1.8.0_152-release-1248-b01 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Windows 10 10.0
```
Plugin Version: 0.6.7 on Windows 10

👍

**Comment by mf-social** [comment]
I know this is closed so I don't know whether anyone is still looking in this one, but just to say that since I reported that this was still a problem back in January, it seems to be working now.  I just started a new project and thought I'd just give it a go and it is working fine.

There's been several updates to AS and a couple of updates to this plugin since, so I don't know which bit fixed it, but it's working fine when I've used it today 👍
