### ISSUE TITLE
What is the difference between publish and finish release?

### ISSUE THREAD

**Issue by roland-d** [OpherV/gitflow4idea#252]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Unclear what these options do.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**
This is not a bug

* **What is the expected behavior?**
Clear what these options do.

* **What is the motivation / use case for changing the behavior?**
Users know what these options do

I checked the linked documents on Git Flow but don't see anything mentioned about the difference between publishing and finishing a release. Perhaps a small note in the readme will be useful.

**Comment by OpherV** [comment]
This is more a question on how to use git flow rather than how to use this plugin.
Please see this link:
https://jeffkreeftmeijer.com/git-flow/

In short "finish release" merges the release to both master and develop while "publish release" pushes the local release branch to be available on the remote repo.

**Comment by ngrcode** [comment]
@OpherV 

how about feature ?
publish vs finish in feature
