### ISSUE TITLE
The IDE Failed to install

### ISSUE THREAD

**Issue by khusamov** [OpherV/gitflow4idea#258]
I can not install the plugin. The error in the screenshot.
![image](https://user-images.githubusercontent.com/4146998/69171988-0932e700-0b0e-11ea-9e8e-a5e941848aae.png)

**Comment by elivin** [comment]
Hi. This is probably not a problem with gitflow4idea plugin. IDE cannot create a new directory for plugins (because it has non-ASCII characters).

Set "Tools install location" in Toolbox settings to directory without cyrillic letters.

![2019-11-20_09-39](https://user-images.githubusercontent.com/12787111/69209605-ad9e4300-0b79-11ea-858c-f6b4efe4f401.png)

![2019-11-20_09-17](https://user-images.githubusercontent.com/12787111/69209492-42547100-0b79-11ea-90b4-98ec8465e24b.png)

**Comment by khusamov** [comment]
Thanks for the answer, but it didn't help. I changed the path of the error, but the error remained.

**Comment by OpherV** [comment]
@khusamov I agree with @elivin this doesn't seem to be related to gitflow4idea

When did it started happening?
Does it happen with every plugin or just this one?
Does it stop if you remove gitflow4idea?

**Comment by khusamov** [comment]
It started now.
This only happens with 'gitflow4idea'
I can not remove it because it is not installed.

**Comment by khusamov** [comment]
I install the plugin from disk. Because the marketplace is not available.

![image](https://user-images.githubusercontent.com/4146998/69229498-902ba200-0b96-11ea-9f4e-d337a06750f4.png)

![image](https://user-images.githubusercontent.com/4146998/69229519-9b7ecd80-0b96-11ea-9604-9bb6936b241a.png)

**Comment by OpherV** [comment]
Please see version 0.7.1
