### ISSUE TITLE
Allows to start a feature/hotfix from a non default branch

### ISSUE THREAD

**Issue by romainfrancez** [OpherV/gitflow4idea#63]
The command line git flow allows to start a feature/hotfix from a non default branch, maybe when the dialog opens in PHP Storm, a dropdown should display which branch to start from with the current checkedout branches (defaulting to the configuration).

**Comment by romainfrancez** [comment]
By the way, if you want I can do it but I'll need help on setuping the environnement to compile the plugin

**Comment by OpherV** [comment]
You're more than welcome to give it a shot. That's what open source is all about :)

The process for setting up the env shouldn't be too hard - here are the general guidelines
https://www.jetbrains.com/idea/help/plugin-development-guidelines.html

**Comment by romainfrancez** [comment]
Ok so I installed the project, but it says it can't find the package git4idea.commands is not found.
Do you know how to solve that?

Thanks,

**Comment by romainfrancez** [comment]
Hi @OpherV,

any tips on how to solve that?

Thanks,

**Comment by OpherV** [comment]
Did you configure your project to use git4idea.jar as a dependency?
![image](https://cloud.githubusercontent.com/assets/3951311/6893473/eb80e034-d6d5-11e4-9b8a-04e49a1f061e.png)

**Comment by szarouski** [comment]
@romainfrancez, I just wonder if you had any luck with that feature? Unfortunately I'll not be able to help with plugin development, but I also find it quite useful to have an option to choose from which branch you want to cut a feature.

**Comment by alextsc** [comment]
I'm currently fixing a couple of things I encountered and I can implement this as well, though I got a couple questions before I finish it up:

1. Is this layout ok? 

![Dialog layout](https://cloud.githubusercontent.com/assets/976780/9704208/01f12810-549e-11e5-839e-e75f0065741b.PNG)

I added a combo for the branch which defaults to $MASTER_BRANCH for "new hotfix" or $DEVELOP_BRANCH for "new feature" when the window is opened. Otherwise the user can pick a particular branch from it.

I also added input validation for the branch name in the dialog, so if you cancel the dialog you dont get the "you have to enter a branch name" error anymore (which I wouldnt expect as a user if I explicitly cancelled the action).

![Validation](https://cloud.githubusercontent.com/assets/976780/9704230/8a957fc2-549e-11e5-9b40-f29edb1c9e3b.PNG)

2. Are there any branches excluded or can a feature/hotfix be branched from any existing branch?
I personally dont use this feature, so just to make sure. 

Alex

**Comment by OpherV** [comment]
Looking good!
I get the use case for starting a feature from a different branch other than develop (maybe from another feature) - but for the hotfix? Why would you start from any other branch other than master? What's the use case?

**Comment by OpherV** [comment]
Well after looking over at the [AVH docs](https://github.com/petervanderdoes/gitflow/wiki/Reference:-git-flow-hotfix) I noticed the implementation does support basing hotfixes on arbitrary branches - so I guess there's no harm in supporting that

**Comment by alextsc** [comment]
Yeah I haven't encountered any situation where I'd need that either. That being said I'd think its best if the plugin mirrors the command line features as close as possible to make switching in either direction easy.
