### ISSUE TITLE
Make compatible with IntelliJ builds 142 and newer

### ISSUE THREAD

**Issue by pvergara** [OpherV/gitflow4idea#78]
Greetings.

I recently downloaded one of the last versions of IntelliJ IDEA (attach) and, from this time, the plugin system don't let me to download your wonderful plugin.

I also tried to install locally but the IntelliJ don't let me do it either. 

Someone knows how to solve the problem?

![screenshot from 2015-08-05 19 57 43](https://cloud.githubusercontent.com/assets/802169/9093499/c24245a0-3bac-11e5-9bba-e31357f2afeb.png)

Best regards

**Comment by jitowix** [comment]
+1

**Comment by natros** [comment]
+1

**Comment by gisphm** [comment]
+1

**Comment by SimenB** [comment]
It's not updated for 142.x

https://github.com/OpherV/gitflow4idea/blob/develop/META-INF/plugin.xml#L12

**Comment by pvergara** [comment]
Hey it works!!!!... you are a F*!#ng genious :-).
Thnx man!!!!

**Comment by OpherV** [comment]
I'm aware of this issue - a new version will be out soon

**Comment by pvergara** [comment]
Thanks you too (and double thanks for your work)

I love to participate in this project when I have time, a resource that is extremely difficult to find nowadays in my life :-(

**Comment by OpherV** [comment]
So turns out this is not an arbitrary fix, as part of the git4idea's (the plugin that gitflow4idea relies on) architecture was changed with the new EAP. I do not recommend trying @SimenB's hack as it might break things when trying to use the plugin.

Specifically this change is problematic:
https://github.com/JetBrains/intellij-community/commit/9146c7a85df2a6cfad57a309a099ef149036c1b5

This also means that once I do get around to changing gitflow4idea to conform to the new git4idea, there will be a split in versions and more recent versions which support 142 will no longer support earlier versions of IntelliJ

**Comment by gala132** [comment]
@OpherV An another update probably broke things again, could you please add support for the new version? (i see no gitflow in PHPStorm 10)
