### ISSUE TITLE
Add support of start feature on all submodule

### ISSUE THREAD

**Issue by audig** [OpherV/gitflow4idea#88]
Sorry for my english, frenchy :)
We are working on a java multi-module project. The project is developed with a backlog which contains story.
Developers need to create some git features linked to the functional story.
They want to start feature on all submodule (create branch from develop branch)
We have tried to add in versioning settings all submodules and the root project with no effect. 

I think it's possible because, i can checkout common branches in git window and all submodule are checked out

For the moment they use this command line : git submodule foreach git flow feature start xxxxxxx and they want to use your plugin

**Comment by OpherV** [comment]
This seems like a super-niche use case, and since I'm not the one using this set up it's not something I can even develop. How about you take a crack at it yourself?

There's a [handy guide](https://github.com/OpherV/gitflow4idea/blob/develop/docs/project_setup.md) on how to build and develop gitflow4idea which should get you up and running in less than 10 minutes. If you ever do implement this, I'll be happy to review and integrate into the codebase.
