### ISSUE TITLE
Plugin Gitflow is incompatible with current installation

### ISSUE THREAD

**Issue by cougil** [OpherV/gitflow4idea#96]
Hi!
I would like to use your plugin in IntelliJ but it seems it is not supported on the last IntelliJ version. I'm trying to install it with IntelliJ 14.1.5 but in the log appears this message:
 INFO - Settings.impl.PluginDownloader - Plugin Gitflow is incompatible with current installation (since:143 until:143.999999) 
Could you update it in order to make it available via the plug-in repository?
Best,

**Comment by OpherV** [comment]
IntelliJ 1.4.1.5 is based on build 141 which is supported by the [previous version](https://github.com/OpherV/gitflow4idea/releases/tag/0.4.4) of gitflow4idea. Please download and use it instead

**Comment by cougil** [comment]
Yes, it works! ;-)
Btw, I suppose I should not update it, should I?
Best,

**Comment by OpherV** [comment]
Since build 143 of IDEA introduced breaking changes - it's not possible to upgrade from gitflow4idea 0.4.4 to 0.4.5

**Comment by julianrupp** [comment]
I kept (and still keep) getting messages in my v14 installation that an update for this plugin was available. Trying to install it just blips the download progress window for a split second, then goes silent, without any error message. After some searching, I stumbled upon this issue here.

In my eyes this problem here is not yet solved.
You may not want to, or be able to, keep compatibility with the old version, but please at least label the new version correctly in JB's plugin repository (compatible versions) so we v14 users don't have to click away the (wrong) "update is available" every single time we start the IDE.

Currently, the last v14 build is 141.2735, and the first v15 release's build is 143.381.42.

Thanks in advance!

**Comment by OpherV** [comment]
@julianrupp I sorted this out in the Jetbrains repo - The message should go away the next time your IDE updates your plugin list repo

**Comment by ShkurtiA** [comment]
Hello, I have the same issue with Android Studio version 2.1.3,  I tried from verison 0.4.9 to 0.4 all of them showed the same message. Is there a way how I can fix this? @OpherV

Thanks

**Comment by OpherV** [comment]
@ShkurtiA Which build is your Android studio?

**Comment by ShkurtiA** [comment]
Hey thanks for you reply. I was trying to install plugin from disk and it didnt work. Than I tried installing it from browsing repositories and it worked. Thanks
